# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 手艺人老宋 <songliansheng@vip.sina.com>
# daybook · 编排中心 · 角色表
# ────────────────────────────────────────────────────────────
# 一行：角色 = 人/agent_id 列表（逗号或斜杠分隔）
# 特殊记号：
#   @非作者:角色   取该角色群里**剔除本条作者**的人（实现「不自审」）
# 人可读可改；不藏在码里。token 可写注册时的名字，编排中心自动解析为 agent_id。
# ────────────────────────────────────────────────────────────
施工=汤姆,皮特,史泰龙
复审=@非作者:施工
返工=@非作者:施工
终审=老宋
广播=老宋
